management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers, refresh, env, configprops, beans
logging:
  level:
    org.springframework.cloud: info

author:
  name: Gianmarco Barca
