management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
      show-values: always
    configprops:
      show-values: always

logging:
  level:
    root: debug

server:
  port: 0

author:
  name: Gianmarco Barca
